### ISSUE TITLE
Error running fitExtractVarPartModel function

### ISSUE THREAD

**Issue by bl24** [GabrielHoffman/variancePartition#19]
[data.level6.match.noOther.valueonly.male.APOE4.neg.txt](https://github.com/GabrielHoffman/variancePartition/files/5024033/data.level6.match.noOther.valueonly.male.APOE4.neg.txt)

[cov.level6.match.noOther.male.APOE4.neg.txt](https://github.com/GabrielHoffman/variancePartition/files/5024038/cov.level6.match.noOther.male.APOE4.neg.txt)

Hello, I've been trying to run the following code using variancePartition 1.18.2 on the 2 text files I've attached:

library(variancePartition)
male.neg.data<-read.table("data.level6.match.noOther.valueonly.male.APOE4.neg.txt",header=TRUE, sep="\t")
male.neg.cov<-read.table("cov.level6.match.noOther.male.APOE4.neg.txt",header=TRUE,sep="\t")

rownames(male.neg.data)<-male.neg.data$X
rownames(male.neg.cov)<-male.neg.cov$X

male.neg.data<-male.neg.data[,-1]
male.neg.cov<-male.neg.cov[,-1]

male.neg.cov$Plate.Bar.Code=factor(male.neg.cov$Plate.Bar.Code)
male.neg.cov$Well.Position=factor(male.neg.cov$Well.Position)
male.neg.cov$educ=as.numeric(male.neg.cov$educ)
male.neg.cov$age_death=as.numeric(male.neg.cov$age_death)
male.neg.cov$bmi=as.numeric(male.neg.cov$bmi)
male.neg.cov$Dx=factor(male.neg.cov$Dx)

form <- ~ (1|Plate.Bar.Code) +(1|Dx) + (1|Well.Position)+educ +age_death+bmi
varPart <- fitExtractVarPartModel(t(male.neg.data), form, male.neg.cov)

But when get to the step using "fitExtractVarPartModel" I get an error message:
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length

Any ideas? Thanks

**Comment by GabrielHoffman** [comment]
There are two issues here:

1) Statistically, the issue is that the formula you specify leads to an "ill-posed" regression that is not full rank.  This is due to the fact there are 29 samples, but you are trying to fit a variable `Well.Position` with 26 levels which approaches the sample size.  This leads to `Well.Position` being highly correlated with the other variables.  So  

```r
nlevels(male.neg.cov$Well.Position)	
nrow(male.neg.cov)

# Evaluate correlation between all pairs of variables
canCorPairs(~Plate.Bar.Code + Dx +educ +age_death+bmi + Well.Position, male.neg.cov)
```
This causes the linear mixed model fitting to crash and not return the usual output.

If `Well.Position` is dropped from the model, it works as expected.  Including it in the model was problematic anyway. 

2) The second issue is a software problem where my code didn't properly catch this error.  I am working on producing a more useful error message

Cheers,
Gabriel
