### ISSUE TITLE
Fitting models with random slope

### ISSUE THREAD

**Issue by jonaszierer** [GabrielHoffman/variancePartition#2]
Hi,

is there a rational for not allowing models with random slopes (throws an error in `checkModelStatu`s). As far as I can see the formula is just passed on to `lme4`, which can fit such models. 

Thanks!
Jonas

**Comment by GabrielHoffman** [comment]
Hi Jonas, 
  If you use the option `showWarnings=FALSE` you can suppress the error. 

But I have found that random slopes are problematic in the context of variancePartition.  Using a random slope means that the variance in each subset of the data (specified by the random slope) is different.  For example, if the slope depends on cell type, then the variance within cell type 1 will be different from cell type 2.  That is ok when using `lmer()` in general, but the goal of variancePartition is to compute variance fractions.  When the variance is different between cell types, the denominator of the variance fraction is now different for each cell type.  This means that the variance fraction will no longer sum to 1 and lose their interpretability.  So I just throw an error instead of giving the user back these challenging results.

Best,
Gabriel

**Comment by jonaszierer** [comment]
Hi Gabriel,

thanks for the quick reply! I'm using `dream` to fit the models and when `dream` calls `checkModelStatus` it uses `showWarnings = F, dream = T`, which means the `Continuous variable cannot be modeled as a random effect` warnings cannot be suppressed.

Actually I'm not even using the variance partition. I was just 'misusing' your package as a convenient way to use mixed models for RNASeq data

Thanks!
Jonas

**Comment by GabrielHoffman** [comment]
Do you have a minimal reproducible example?

**Comment by jonaszierer** [comment]
By just slightly adapting the example from [bioconductor](https://bioconductor.org/packages/release/bioc/vignettes/variancePartition/inst/doc/dream.html)

```
library('variancePartition')
library('edgeR')
library('doParallel')
data(varPartDEdata)

isexpr = rowSums(cpm(countMatrix)>0.1) >= 3

# Standard usage of limma/voom
genes = DGEList( countMatrix )
genes = calcNormFactors( genes )
design = model.matrix( ~ Disease, metadata)
vobj_tmp = voom( genes, design, plot=FALSE)

# apply duplicateCorrelation
dupcor <- duplicateCorrelation(vobj_tmp,design,block=metadata$Individual)

# run voom considering the duplicateCorrelation results
# in order to compute more accurate precision weights
# Otherwise, use the results from the first voom run
vobj = voom( genes, design, plot=FALSE, block=metadata$Individual, correlation=dupcor$consensus)


# The variable to be tested should be a fixed effect
metadata$run_order <- rep(1:(nrow(metadata)/2), 2)
metadata$batch     <- sort(rep(c("A", "B"), nrow(metadata)/2))

form <- ~ Disease + (1 + run_order | batch)

# Get the contrast matrix for the hypothesis test
L = getContrast( vobj, form, metadata, "Disease1")

# Fit the dream model on each gene
# Apply the contrast matrix L for the hypothesis test
# By default, uses the Satterthwaite approximation for the hypothesis test
fitmm = dream( vobj, form, metadata, L)
```

now the `fitmm` fails with `Continuous variable cannot be modeled as a random effect: run_order`; `showWarnings = F` does not solve that

**Comment by GabrielHoffman** [comment]
Yes, I see that dream throws an error.  But I am not clear about what the ideal outcome is.  Here are two options
1) dream should not throw an error and perform the analysis.
2) dream should give a more informative error message  

The issue is when I run this formula directly in lmer, I also get a stern warning:
```
> y = t(vobj$E[4,,drop=FALSE])
> fit = lmer( y ~ Disease + (1+ run_order | batch), metadata)
singular fit
Warning message:
In as_lmerModLT(model, devfun) :
  Model may not have converged with 1 eigenvalue close to zero: 9.3e-11
```
I tried a few other variation of the formula and response variable with the random slopes model, but they gave a `singular fit`.

So it seems like `dream` should also give a warning or an error, but I have to figure out which. 

 I will  
1) I have to look into `checkModelStatus` and debug this  
2) Make sure the flag `showWarnings` actually works and is documented.

Hopefully by the end of the week.

Thanks for the bug report.    Let me know if I need to fix anything else

Cheers, 
- Gabriel

**Comment by jonaszierer** [comment]
I think the convergence warning is ok. The model doesn't converge because it's just random data. And if this happens with real data the warning is important to the user to check the model.

The warning I was talking about is the `Continuous variable cannot be modeled as a random effect:` which stops dream from calculating the models. That seems unnecessary for me...

Thanks a lot!
Jonas

**Comment by GabrielHoffman** [comment]
Jonas, 
I have made changes in the backend so that you can new run random slope models using dream.  you can also override the errors:  

I also added to the vignette and will show up in the next freeze:
Note that many warnings and errors can be overridden by specifying `suppressWarnings=TRUE` for`dream()` and `showWarnings=FALSE` for `fitExtractVarPartModel()` and `fitVarPartModel()`.

For now you can download v1.13.2 from GitHub and try it out.  Let me know if it works as expected.

After you give it a try, I can push the change to the Bioconductor release branch.

-- Gabriel

**Comment by GabrielHoffman** [comment]
Jonas, 
  Any issues with the new version?

- Gabriel

**Comment by jonaszierer** [comment]
Sorry for the delay. Works like a charm, thanks!
