### ISSUE TITLE
For a fixed effects model, the answer can depend on the order of terms in the formula

### ISSUE THREAD

**Issue by NikTuzov** [GabrielHoffman/variancePartition#30]
Dear Dr. Hoffman:

Part 3 of the documentation:

http://bioconductor.org/packages/release/bioc/vignettes/variancePartition/inst/doc/variancePartition.pdf

suggests that “the effect of each variable is assessed while correcting for all others”. The attached R code demonstrates that it doesn’t have to be the case when all of the effects in the model are fixed. As a result, the variance fractions can be dependent on the order of terms in the formula.

It happens because when anova() is used to extract the sums of squares, one ends up with sequential (Type I) sums of squares whereas the documentation implies that Type III sums of squares are used. The following link provides more details on anova():

https://www.r-bloggers.com/2011/03/anova-%E2%80%93-type-iiiiii-ss-explained/

Regards,
Nik Tuzov, PhD

[variancePartition_Github_ticket.zip](https://github.com/GabrielHoffman/variancePartition/files/6219601/variancePartition_Github_ticket.zip)

**Comment by GabrielHoffman** [comment]
Hi Nik, 
Thanks for the bug report.  I have worked out a fix on the statistical side.  I will integrate it into package and test it out this week.  

Best,
Gabriel

**Comment by NikTuzov** [comment]
Thank you for responding so quickly.

Regards,
Nik

**Comment by GabrielHoffman** [comment]
Hi Nik, 
I had assumed (incorrectly) that `anova` returned the sum of squares from a single model fit.  But based on your report, it appears to be more complicated than that.  The new version of `calcVarPart()` extracts the sum of squares from a single model fit to partition the total sum of squares into multiple components.  The [code](https://github.com/GabrielHoffman/variancePartition/blob/8e43465518839183b2276fd9ce43cf7739931ed5/R/calcVarPart.R#L88) from the new version is adapted from the code from the linear mixed model case.  Since the new version replaces `anova()`, which uses a stepwise approach to fit linear models with an increasing number of variables, with a method that fits the linear model just once, the results from the new version will be very slightly different than before.  

Here are the new results with `variancePartition v1.21.4` from this GitHub repo:

```r
library('variancePartition')

data(varPartData)

form <- ~ Age + Individual + Tissue + Batch
varPart <- fitExtractVarPartModel( geneExpr, form, info)
#> Loading required package: Matrix
#> 
#> Total:1 s
vp <- sortCols( varPart )
head(vp, 1)
#>       Individual     Tissue       Batch          Age  Residuals
#> gene1  0.9173543 0.02042786 0.004600206 9.797375e-05 0.05751965

form.2 <- ~ Individual + Tissue + Batch + Age
varPart.2 <- fitExtractVarPartModel(geneExpr, form.2, info)
#> 
#> Total:1 s
vp.2 <- sortCols(varPart.2)
head(vp.2, 1)
#>       Individual     Tissue       Batch          Age  Residuals
#> gene1  0.9173543 0.02042786 0.004600206 9.797375e-05 0.05751965
```

Here are the results directly using `lm()`

```r
response <- geneExpr[1,]
fit <- lm(response ~ Age + Individual + Tissue + Batch, info)
calcVarPart(fit)
#>          Age   Individual       Tissue        Batch    Residuals 
#> 9.797375e-05 9.173543e-01 2.042786e-02 4.600206e-03 5.751965e-02

fit2 <- lm(response ~ Individual + Tissue + Batch + Age, info)
calcVarPart(fit2)
#>   Individual       Tissue        Batch          Age    Residuals 
#> 9.173543e-01 2.042786e-02 4.600206e-03 9.797375e-05 5.751965e-02
```

I it will take some more work to update the Bioconductor package

**Comment by NikTuzov** [comment]
Hello Gabriel:

Thank you for fixing it. 
Your new Type III SS are close to correct values, but not quite. I attached another R file where Type III SS are obtained in two different ways, generating identical results. In addition, I verified those Type III SS outside R and they check out. I don't know exactly why your fix is slightly off, but it should be easy to modify it. Using drop1() approach seems the most convenient way.

Regards,
Nik

[variancePartition_extract_type_3.zip](https://github.com/GabrielHoffman/variancePartition/files/6245253/variancePartition_extract_type_3.zip)

**Comment by GabrielHoffman** [comment]
Hi Nik, 

The discrepancy is due to the fact that ANOVA is aimed at hypothesis testing, while in variance partitioning we are only interested in the variance fractions.  My understanding of ANOVA III is that `drop1()` evaluates the difference in sum of squares after dropping each term from the model and refitting.  This is good for hypothesis testing and comparing the sum of squares from the full and null models.  

However, in variance partitioning we need the sum of squares evaluated on *a single model fit with no refitting*.  The sum of squares ratios can't now be applied to hypothesis testing, but it is simple enough to compute the variance fractions.

Gabriel

**Comment by NikTuzov** [comment]
Gabriel:

1)	Type III SS can be obtained without refitting, but the process is rather sophisticated. As far as I know, it was developed by SAS a long time ago. It is based on the so-called “Type III estimable functions”:

https://support.sas.com/documentation/onlinedoc/stat/131/introglmest.pdf

If we ran that linear model of ours in PROC GLM or MIXED, then of course SAS wouldn’t refit it four times. It would compute the “estimable functions” and then use them to extract Type III SS and p-values from the full fit. 

I tried to find that kind of functionality in R, but to no avail. Therefore, drop1() is simply a brute force approach to obtain the same answer that one can also obtain without refitting. 

On the other hand, the computation of estimable functions is not free either. Unless the number of terms in the model is very large, refitting should not be much slower than the estimable functions approach or the fix that you just developed.

2)	Most important, variancePartition documentation states that “the effect of each variable is assessed while correcting for all others” which is equivalent to using Type III SS. Your fix does not use Type III SS, so it is not consistent with the documentation. While in our toy example with gene1 the discrepancy is practically negligible, it can be quite large for real data sets.

Regards,
Nik

**Comment by GabrielHoffman** [comment]
Since I updated the `calcVarPart()` method I now updated the [documentation](https://hoffmg01.u.hpc.mssm.edu/software/variancePartition/variancePartition.pdf) (also linked on README).  See page 11:

variancePartition fits a linear (mixed) model that jointly considers the contribution of all specified variables on the expression of each gene. It uses a multiple regression model so that the effect of each variable is assessed while jointly accounting for all others [1].

[1] Standard ANOVA implemented in R involves refitting the model while dropping terms, but is aimed at hypothesis testing. variancePartition’s `calcVarPart` is aimed at estimating variance fractions. It uses a single fit of the linear (mixed) model and evaluates the sum of squares of each term and the sum of squares of the total model fit.

**Comment by NikTuzov** [comment]
The phrase "the effect of each variable is assessed while jointly accounting for all others" still implies that Type III SS are computed, which is not the case. It would be nice if you note stated explicitly that you compute your own version of SS that differs from Type III SS. 

As for hypothesis testing, it is true that Type III SS can be used to obtain Type III p-values, but it doesn't mean that Type III SS are somehow less suitable for variance partitioning. The only relevant question is: which SS describes the amount of variance explained by a model term given that all the other terms have been taken into account? The answer happens to be Type III SS. The questions of how it is computed (by dropping terms or some other method) and whether it can also be used for hypothesis testing are irrelevant.

**Comment by NikTuzov** [comment]
Hello Gabriel:

I looked at Section 7 of your vignette paper and at the code. Apparently, you are using the post hoc calculation, formula (4), to get the variance components for fixed factors. Your paper says that “for a fixed effects model, this corresponds to the sum of squares for each component of the model”. I’m not sure if it is true in general (it may only be true for an orthogonal design). Further, this line of code:

as.array(fixedSS[[key]] / sum(fixedSS) * ssFixedTotal)

means that the fixed variance components are re-normalized just amongst themselves first. Even if it were possible to get the Type III SS via the post hoc approach, the final answer would be somewhat off because of that re-normalization which is not included in your paper.

The same re-normalization issue is present when the design contains both random and fixed (quantitative) terms.
