### ISSUE TITLE
setting up the correct form for dream analysis

### ISSUE THREAD

**Issue by dahrendorff** [GabrielHoffman/variancePartition#33]
Hi Dr. Hoffman,

I would like to use dream for my 2 timepoint RNA-sequencing data and have a little bit of trouble specifying the form.  In my data some participants did not have the disease of interest at baseline and developed it by timepoint 2 while others had the disease at baseline already and some never developed the disease. I would like to capture how the change in disease status affects the gene expression and the covariates I would like to include are Sex as well as a range of cell proportions including B_Cells , CD4T , Monocytes , NK_cells , CD8T. I would also like to include an interaction term time:disease as a time varying covariate. With regard to the cell proportions, want to use them as fixed effects as well only including the baseline measurement (I have added 0s for the 2nd timepoints in my metadata). My form so far looks like this: 

form <- ~ (disease+0|resp) + (1|resp) + Sex + B_Cells + CD4T + Monocytes + NK_cells + CD8T

It seems to run okay but I am not sure if this is the best way to do it. Do you have any advice?
My  metadata for the first 5 participants  looks like this:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/jdahr/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/jdahr/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/jdahr/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>

rnaid | resp | disease | wave | Sex | B_Cells | CD4T | Monocytes | NK_cells | CD8T
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
2009300244_2 | 12584 | 1 | base | Male | 0.193322 | 0.288841 | 0.410726 | 0.107112 | 0
2009310031_5 | 1163 | 0 | base | Female | 0 | 0.365396 | 0.531808 | 0.102796 | 0
2009310032_9 | 10718 | 0 | base | Male | 0.253984 | 0.35755 | 0.257725 | 0.130742 | 0
2011250011_76 | 1163 | 1 | w4 | Female | 0 | 0 | 0 | 0 | 0
2009310298_42 | 599 | 0 | base | Female | 0.210174 | 0.355125 | 0.314209 | 0.06543 | 0.024351
2011270137_92 | 599 | 1 | w4 | Female | 0 | 0 | 0 | 0 | 0
2009310359_50 | 100007 | 0 | base | Female | 0.211966 | 0.436188 | 0.274483 | 0.077363 | 0
2011250043_76 | 100007 | 1 | w4 | Female | 0 | 0 | 0 | 0 | 0
2011250069_81 | 12584 | 1 | w4 | Male | 0 | 0 | 0 | 0 | 0
2011250199_104 | 10718 | 0 | w4 | Male | 0 | 0 | 0 | 0 | 0

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

</body>

</html>

Thank you so much for you time,

Jan Dahrendorff

**Comment by GabrielHoffman** [comment]
Hi Jan, 
Thanks for your question.  Here are some thoughts:

If you haven't observed data at given time points, you shouldn't add it in.  The 0's will appear as outliers in the cell type composition distribution, and you don't have gene expression at that time point anyway.

First, let's talk about including cell composition as covariates.  Including all cell fractions in the same model is problematic because the fractions sum to 1.  See [description here](https://www.biorxiv.org/content/10.1101/2020.10.05.326405v1.full)

The relevant section reads:

> While computational deconvolution was used to estimate the fraction of four cell types, the constraint that the four fractions sum to 1.0 for each sample means that the fractions really span only three dimensions (i.e., knowing three determines the fourth). Including this set of low rank covariates in a regression model is problematic. To address this issue, the four fractions were transformed into three variables using the isometric log ratio (24) to create covariates cellFrac_ilr_1, cellFrac_ilr_2, cellFrac_ilr_3. This transformation is invariant to scaling and reordering of the cell fraction variables; however, each resulting variable is a function of multiple cell fractions so they can’t be interpreted individually.

> The regression formula used for differential expression analysis was: ~ Diagnosis + Sex + RIN + IntronicRate + IntragenicRate + IntergenicRate + rRNARate + Institution*(ageOfDeath + cellFrac_ilr_1 + cellFrac_ilr_2 + cellFrac_ilr_3)

Transforming the cell fractions will solve this problem.  See code [here](https://github.com/CommonMindConsortium/covarr-de/blob/edb521f6d4c326f61409d5e3b18a10973dbd7a55/combined_analysis/combine_all_DLPFC.Rmd#L369)

In the formulas below I use `[cell composition variables]` as a placeholder for these transformed fractions.

I am assuming `wave` indicates the time point.

I would recommend first testing cases versus controls with a formula like `~ disease + (1|resp) + wave + Sex + [cell composition variables]`.  You can then test if the `disease` coefficient is different from zero to see if there is a disease effect after removing the variation across waves and accounting for the repeated measurement of donors.

Next, you can test if there as a wave-by-disease interaction effect using the formula `~ disease + wave + disease:wave + (1|resp) + Sex + [cell composition variables]`.  You can then test the coefficient `disease:wave` to test of the association between disease and gene expression changes between the two waves.

Gabriel

**Comment by dahrendorff** [comment]
Hi and thank you so much for your advice and recommendations. I appreciate it. Correct, wave indicates the timepoint.  I do have cell proportion data for both timepoints but I removed the cell proportions for the 2nd timepoint (w4) because I figured they would be a varying coefficient and in the variance partition manual on page 37 (https://www.bioconductor.org/packages/release/bioc/vignettes/variancePartition/inst/doc/variancePartition.pdf) it says “Only one varying coefficient term can be specified”. Did I understand that correctly or should I keep the cell proportions for the 2nd timepoint? 
With regard to using [cell composition variables] as a placeholder for these transformed fractions do I need to transform mine into 4 variables if I have 5 different cell types considering the four fractions from the paper you mention were transformed into three variables?

Jan
