### ISSUE TITLE
Confidence intervals of log2(Fold_Change)

### ISSUE THREAD

**Issue by jgockley62** [GabrielHoffman/variancePartition#48]
Hi @GabrielHoffman,

I'm trying to see if I can calculate the 95% interval of log2(FC) from `variancePartition::dream()`{:.language-r}. I've used `variancePartition::varPartConfInf()`{:.language-r} but the CI's don't make sense given my log2(FC).  Are they a percent of the Log2(FC)? or am I thinking about this process incorrectly?

**Comment by GabrielHoffman** [comment]
In order to summarize the results you can use `topTable()` just like in the `limma` package.  Here is code to compute the confidence interval for results from `dream()` or `limma::lmFit()`.  Following the example in `?dream`:
```r
topTable( fit, coef="Batch2", confint=TRUE )
```

`variancePartition::varPartConfInf()` has a different application.  It uses bootstrap sampling to get 95% CI for the variance fractions from a variance partition analysis

Gabriel

**Comment by GabrielHoffman** [comment]
The effect of `eBayes()` in `limma` and `dream` is small with sufficient sample size
