### ISSUE TITLE
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length

### ISSUE THREAD

**Issue by evaesquinas** [GabrielHoffman/variancePartition#64]
Dear Dr. Hoffman, 

I am trying to run `variancePartition` and `fitExtractVarPartModel()` to get the fraction of variance explained by each variable added in the formula. In addition, I have previously adjusted my data by 1 variable using `removeBatchEffect` from `limma`. 
In order to see the fraction of variance by this variable after the adjustment, I run `fitExtractVarPartModel`... but I got this error:
```
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length
Calls: fitExtractVarPartModel ... row.names<- -> row.names<-.data.frame -> .rowNamesDF<-
In addition: Warning message:
In matrix(unlist(varPart), nrow = length(varPart), byrow = TRUE) :
  data length [3828] is not a sub-multiple or multiple of the number of rows [1915]
Execution halted
```
If I run the function again with this variable + another variable, I get the same error but not the warning message.
```
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length
Calls: fitExtractVarPartModel ... row.names<- -> row.names<-.data.frame -> .rowNamesDF<-
Execution halted
```

On the other hand, if I run `fitExtractVarPartModel` with a DIFFERENT VARIABLE (and NOT adding the variable that I adjusted for), the run works and I don't get any error.

Note 1: The columns (samples) from `exprObj` (log2(normalized counts + 1)) follows the same order as you can find in the column where the samples are in `data`. The `data` has the samples as rownames and `exprObj` is a matrix.
Although I saw that the example that it appears in the vignette has negative values and I have confirmed that my data works when I have a different variable in my formula, it is important to say (just in case) that the adjusted normalized counts contain negative values for some genes.

Note 2: I have tried to run `variancePartition` after having adjusted by the same variable using `ComBat-Seq`  and I have run the same models and it works. I don't get any errors/warnings.

**Do you know what could be the reason of the error?**

Any help would be very appreciated.

Thanks very much in advance

My R session:
```
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods
[8] base

other attached packages:
 [1] tidyr_1.2.0              biomaRt_2.48.3        dplyr_1.0.8    
 [4] variancePartition_1.22.0 Biobase_2.52.0         BiocGenerics_0.38.0      
 [7] scales_1.1.1             BiocParallel_1.26.0       limma_3.48.3
[10] ggplot2_3.3.5

loaded via a namespace (and not attached):
 [1] nlme_3.1-152           bitops_1.0-7           matrixStats_0.59.0
 [4] pbkrtest_0.5.1         bit64_4.0.5            filelock_1.0.2
 [7] doParallel_1.0.17      progress_1.2.2         httr_1.4.2
[10] GenomeInfoDb_1.28.0    tools_4.1.2            backports_1.4.1
[13] utf8_1.2.2             R6_2.5.1               KernSmooth_2.23-20
[16] DBI_1.1.2              colorspace_2.0-2       withr_2.4.3
[19] tidyselect_1.1.1       prettyunits_1.1.1      curl_4.3.2
[22] bit_4.0.4              compiler_4.1.2         cli_3.1.1
[25] xml2_1.3.3             labeling_0.4.2         caTools_1.18.2
[28] readr_2.1.2            rappdirs_0.3.3         stringr_1.4.0
[31] digest_0.6.29          minqa_1.2.4            colorRamps_2.3
[34] XVector_0.32.0         pkgconfig_2.0.3        lme4_1.1-28
[37] dbplyr_2.1.1           fastmap_1.1.0          rlang_1.0.1
[40] RSQLite_2.2.7          farver_2.1.0           generics_0.1.2
[43] gtools_3.9.2           RCurl_1.98-1.3         magrittr_2.0.2
[46] GenomeInfoDbData_1.2.6 Matrix_1.3-2           Rcpp_1.0.8
[49] munsell_0.5.0          S4Vectors_0.30.0       fansi_1.0.2
[52] lifecycle_1.0.1        stringi_1.7.6          MASS_7.3-54
[55] zlibbioc_1.38.0        gplots_3.1.1           plyr_1.8.6
[58] BiocFileCache_2.0.0    grid_4.1.2             blob_1.2.2
[61] crayon_1.4.2           lattice_0.20-44        Biostrings_2.60.1
[64] splines_4.1.2          hms_1.1.1              KEGGREST_1.32.0
[67] pillar_1.7.0           boot_1.3-28            reshape2_1.4.4
[70] codetools_0.2-18       stats4_4.1.2           XML_3.99-0.6
[73] glue_1.6.1             vctrs_0.3.8            png_0.1-7
[76] nloptr_2.0.0           tzdb_0.2.0             foreach_1.5.2
[79] gtable_0.3.0           purrr_0.3.4            assertthat_0.2.1
[82] cachem_1.0.6           broom_0.7.12           tibble_3.1.6
[85] iterators_1.0.14       AnnotationDbi_1.54.1   memoise_2.0.0
[88] IRanges_2.26.0         ellipsis_0.3.2
```

**Comment by GabrielHoffman** [comment]
Can you send a reproducible example of the first issue
________________________________
From: evaesquinas ***@***.***>
Sent: Monday, August 8, 2022 7:01:56 AM
To: GabrielHoffman/variancePartition ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [GabrielHoffman/variancePartition] Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length (Issue #64)

USE CAUTION: External Message.

Dear Dr. Hoffman,

I am trying to run variancePartition and fitExtractVarPartModel() to get the fraction of variance explained by each variable added in the formula. In addition, I have previously adjusted my data by 1 variable using removeBatchEffect from limma.
In order to see the fraction of variance by this variable after the adjustment, I run fitExtractVarPartModel... but I got this error:

Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length
Calls: fitExtractVarPartModel ... row.names<- -> row.names<-.data.frame -> .rowNamesDF<-
In addition: Warning message:
In matrix(unlist(varPart), nrow = length(varPart), byrow = TRUE) :
  data length [3828] is not a sub-multiple or multiple of the number of rows [1915]
Execution halted


If I run the function again with this variable + another variable, I get the same error but not the warning message.

Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length
Calls: fitExtractVarPartModel ... row.names<- -> row.names<-.data.frame -> .rowNamesDF<-
Execution halted


On the other hand, if I run fitExtractVarPartModel with a DIFFERENT VARIABLE (and NOT adding the variable that I adjusted for), the run works and I don't get any error.

Note 1: The columns (samples) from exprObj (log2(normalized counts + 1)) follows the same order as you can find in the column where the samples are in data. The data has the samples as rownames and exprObj is a matrix.

Note 2: I have tried to run variancePartitition after having adjusted by the same variable using ComBat-Seq and I have run the same models and it works. I don't get any errors/warnings.

Do you know what could be the reason of the error?

Any help would be very appreciated.

Thanks very much in advance

My R session:

R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods
[8] base

other attached packages:
 [1] tidyr_1.2.0              biomaRt_2.48.3           targetidwp4_0.1.0
 [4] dplyr_1.0.8              variancePartition_1.22.0 Biobase_2.52.0
 [7] BiocGenerics_0.38.0      scales_1.1.1             BiocParallel_1.26.0
[10] limma_3.48.3             ggplot2_3.3.5

loaded via a namespace (and not attached):
 [1] nlme_3.1-152           bitops_1.0-7           matrixStats_0.59.0
 [4] pbkrtest_0.5.1         bit64_4.0.5            filelock_1.0.2
 [7] doParallel_1.0.17      progress_1.2.2         httr_1.4.2
[10] GenomeInfoDb_1.28.0    tools_4.1.2            backports_1.4.1
[13] utf8_1.2.2             R6_2.5.1               KernSmooth_2.23-20
[16] DBI_1.1.2              colorspace_2.0-2       withr_2.4.3
[19] tidyselect_1.1.1       prettyunits_1.1.1      curl_4.3.2
[22] bit_4.0.4              compiler_4.1.2         cli_3.1.1
[25] xml2_1.3.3             labeling_0.4.2         caTools_1.18.2
[28] readr_2.1.2            rappdirs_0.3.3         stringr_1.4.0
[31] digest_0.6.29          minqa_1.2.4            colorRamps_2.3
[34] XVector_0.32.0         pkgconfig_2.0.3        lme4_1.1-28
[37] dbplyr_2.1.1           fastmap_1.1.0          rlang_1.0.1
[40] RSQLite_2.2.7          farver_2.1.0           generics_0.1.2
[43] gtools_3.9.2           RCurl_1.98-1.3         magrittr_2.0.2
[46] GenomeInfoDbData_1.2.6 Matrix_1.3-2           Rcpp_1.0.8
[49] munsell_0.5.0          S4Vectors_0.30.0       fansi_1.0.2
[52] lifecycle_1.0.1        stringi_1.7.6          MASS_7.3-54
[55] zlibbioc_1.38.0        gplots_3.1.1           plyr_1.8.6
[58] BiocFileCache_2.0.0    grid_4.1.2             blob_1.2.2
[61] crayon_1.4.2           lattice_0.20-44        Biostrings_2.60.1
[64] splines_4.1.2          hms_1.1.1              KEGGREST_1.32.0
[67] pillar_1.7.0           boot_1.3-28            reshape2_1.4.4
[70] codetools_0.2-18       stats4_4.1.2           XML_3.99-0.6
[73] glue_1.6.1             vctrs_0.3.8            png_0.1-7
[76] nloptr_2.0.0           tzdb_0.2.0             foreach_1.5.2
[79] gtable_0.3.0           purrr_0.3.4            assertthat_0.2.1
[82] cachem_1.0.6           broom_0.7.12           tibble_3.1.6
[85] iterators_1.0.14       AnnotationDbi_1.54.1   memoise_2.0.0
[88] IRanges_2.26.0         ellipsis_0.3.2

**Comment by evaesquinas** [comment]
First of all, thanks very much for your reply.
Due I am working with sensitive data, I have produced a similar example that gives me the error. Note that I tried to reduce the example as much as I could to get the error and to avoid pasting a huge example.
Find attached the data, since it is quite big and I cannot upload it as a comment.

[pheno.txt](https://github.com/GabrielHoffman/variancePartition/files/9289979/pheno.txt)
[cts.txt](https://github.com/GabrielHoffman/variancePartition/files/9289978/cts.txt)

```
library(variancePartition)
library(dplyr)
library(tidyr)
cts <- read.csv("./cts.txt", sep="")
pheno <- read.csv("./pheno.txt", sep="")

categorical_variables <- c("Sample", "Var1", "Var2")
pheno[,categorical_variables] <- lapply(pheno[,categorical_variables],as.factor)
str(pheno)

cts.mat <- as.matrix(cts)
```

## **Model 1**
```
set.seed(11344)
model1 = ~ (1|Var1)
varPart <- fitExtractVarPartModel(cts.mat, model1, pheno)
set.seed(NULL)
```
It works without any problem.

## **Model 2**
```
set.seed(11344)
model2 = ~ (1|Var2) 
varPart <- fitExtractVarPartModel(cts.mat, model2, pheno)
set.seed(NULL)
```
I get this error:
```
Dividing work into 100 chunks...
Total:4 s
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length
Calls: fitExtractVarPartModel ... row.names<- -> row.names<-.data.frame -> .rowNamesDF<-
In addition: Warning message:
In matrix(unlist(varPart), nrow = length(varPart), byrow = TRUE) :
  data length [30] is not a sub-multiple or multiple of the number of rows [16]
Execution halted
```

## **Model 3**
```
model3 = ~ (1|Var1) + (1|Var2)
set.seed(11344)
varPart <- fitExtractVarPartModel(cts.mat, model3, pheno)
set.seed(NULL)
```
I get this error:
```
Error in if (inherits(possibleError, "error") && grep("the fixed-effects model matrix is column rank deficient",  :
  missing value where TRUE/FALSE needed
Calls: fitExtractVarPartModel -> fitExtractVarPartModel -> .fitExtractVarPartModel
Execution halted
```

Note that those **errors were obtained using slurm** (I just launched my R script in the cluster that I am using, writing this piece of code at the beginning of my R script `#!/usr/bin/Rscript --vanilla`). 

If I run each model in my personal computer (same version of the package) I get slightly different errors.

**Model 1:**
```
Dividing work into 100 chunks...

Total:4 s
There were 50 or more warnings (use warnings() to see the first 50)
>   set.seed(NULL)
> warnings()
Warning messages:
1: In serialize(data, node$con, xdr = FALSE) :
  'package:stats' may not be available when loading
2: In serialize(data, node$con, xdr = FALSE) :
  'package:stats' may not be available when loading
(the rest of the warnings are the same)
```

**Model 2:**  I don't get the previous error `In matrix(unlist(varPart), nrow = length(varPart), byrow = TRUE) : data length [30] is not a sub-multiple or multiple of the number of rows [16]`
```
Dividing work into 100 chunks...

Total:1 s
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length
In addition: Warning messages:
1: In serialize(data, node$con, xdr = FALSE) :
  'package:stats' may not be available when loading
(9 more warnings as the first one)
```

**Model 3**  (I don't get the same previous error)
```
Dividing work into 100 chunks...

Total:1 s
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length
In addition: There were 12 warnings (use warnings() to see them)
>   set.seed(NULL)
> warnings()
Warning messages:
1: In optwrap(optimizer, devfun, getStart(start, rho$pp),  ... :
  convergence code -4 from nloptwrap: NLOPT_ROUNDOFF_LIMITED: Roundoff errors led to a breakdown of the optimization algorithm. In this case, the returned minimum may still be useful. (e.g. this error occurs in NEWUOA if one tries to achieve a tolerance too close to machine precision.)
2: In optwrap(optimizer, devfun, getStart(start, rho$pp),  ... :
  convergence code -4 from nloptwrap: NLOPT_ROUNDOFF_LIMITED: Roundoff errors led to a breakdown of the optimization algorithm. In this case, the returned minimum may still be useful. (e.g. this error occurs in NEWUOA if one tries to achieve a tolerance too close to machine precision.)
3: In serialize(data, node$con, xdr = FALSE) :
  'package:stats' may not be available when loading

(remaining warnings are the same as the 3rd one)
```

Note that I use seeds just in case to have the same outputs (although it doesn't usually help and I am getting different errors...)

I hope this can help you a bit more to understand my problem. 

Thanks very much in advance

**Comment by GabrielHoffman** [comment]
First, some errors are fixed others give more informative messages in the latest version v1.27.3 (https://diseaseneurogenomics.github.io/variancePartition/).  I have made substantial fixes since v.1.22.0.

Second, lets look at model 2, but focus on the 5th gene:
```r
set.seed(11344)
model2 = ~ (1|Var2) 
varPart <- fitExtractVarPartModel(cts.mat[5,,drop=FALSE], model2, pheno)

# Warning messages:
# 1: In optwrap(optimizer, devfun, getStart(start, rho$pp), lower = rho$lower,  :
#  convergence code -4 from nloptwrap: NLOPT_ROUNDOFF_LIMITED: Roundoff errors led
# to a breakdown of the optimization algorithm. In this case, the returned minimum 
# may still be useful.  (e.g. this error occurs in NEWUOA if one tries to achieve 
# a tolerance too close to machine precision.)
```

This is more an issue with the data than with the software.  Looking at the expression of gene 5 versus `Var2`:
```r
df = data.frame(Var2 = pheno$Var2, expr = cts.mat[5,])
df[order(df$Var2),]
```
We see that there is no variation *within* category.  This means that there is no residual variance, and the model fit fails. 

```r
> df[order(df$Var2),]
     Var2          expr
S116    1 -1.981364e-03
S117    1 -1.981364e-03
S118    1 -1.981364e-03
S1      2  4.489186e-05
S2      2  4.489186e-05
S3      3  9.136233e-06
S4      3  9.136233e-06
S5      3  9.136233e-06
S6      3  9.136233e-06
S7      3  9.136233e-06
S8      3  9.136233e-06
S9      3  9.136233e-06
S13     3  9.136233e-06
S17     3  9.136233e-06
S18     3  9.136233e-06
S19     3  9.136233e-06
S20     3  9.136233e-06
S21     3  9.136233e-06
S22     3  9.136233e-06
S10     4  2.412923e-05
S11     4  2.412923e-05
S12     4  2.412923e-05
S14     4  2.412923e-05
S15     4  2.412923e-05
S16     4  2.412923e-05
S24     4  2.412923e-05
S25     4  2.412923e-05
S26     4  2.412923e-05
S28     5  9.884335e-06
S31     5  9.884335e-06
S32     5  9.884335e-06
S34     5  9.884335e-06
S36     5  9.884335e-06
S41     5  9.884335e-06
S42     5  9.884335e-06
S46     5  9.884335e-06
S47     5  9.884335e-06
S48     5  9.884335e-06
S51     5  9.884335e-06
S52     5  9.884335e-06
S54     5  9.884335e-06
S29     6  9.815644e-06
S30     6  9.815644e-06
S33     6  9.815644e-06
S35     6  9.815644e-06
S37     6  9.815644e-06
S38     6  9.815644e-06
S39     6  9.815644e-06
S40     6  9.815644e-06
S43     6  9.815644e-06
S44     6  9.815644e-06
S45     6  9.815644e-06
S49     7 -8.161759e-05
S50     7 -8.161759e-05
S56     7 -8.161759e-05
S57     7 -8.161759e-05
S58     7 -8.161759e-05
S59     7 -8.161759e-05
S60     7 -8.161759e-05
S61     7 -8.161759e-05
S62     7 -8.161759e-05
S63     7 -8.161759e-05
S64     7 -8.161759e-05
S71     7 -8.161759e-05
S55     8  2.274638e-05
S65     8  2.274638e-05
S66     8  2.274638e-05
S67     8  2.274638e-05
S68     8  2.274638e-05
S69     8  2.274638e-05
S70     8  2.274638e-05
S74     8  2.274638e-05
S23     9  9.736041e-06
S27     9  9.736041e-06
S53     9  9.736041e-06
S72     9  9.736041e-06
S73     9  9.736041e-06
S75     9  9.736041e-06
S76     9  9.736041e-06
S77     9  9.736041e-06
S78     9  9.736041e-06
S80     9  9.736041e-06
S83     9  9.736041e-06
S85     9  9.736041e-06
S93     9  9.736041e-06
S97     9  9.736041e-06
S102    9  9.736041e-06
S79    10  4.058674e-05
S81    10  4.058674e-05
S82    10  4.058674e-05
S86    10  4.058674e-05
S89    10  4.058674e-05
S91    10  4.058674e-05
S92    10  4.058674e-05
S94    10  4.058674e-05
S95    10  4.058674e-05
S96    10  4.058674e-05
S98    10  4.058674e-05
S101   10  4.058674e-05
S84    11  2.747669e-05
S87    11  2.747669e-05
S88    11  2.747669e-05
S90    11  2.747669e-05
S99    11  2.747669e-05
S100   11  2.747669e-05
S103   12  2.413696e-05
S104   12  2.413696e-05
S105   12  2.413696e-05
S106   12  2.413696e-05
S107   12  2.413696e-05
S109   12  2.413696e-05
S110   12  2.413696e-05
S111   12  2.413696e-05
S113   12  2.413696e-05
S114   12  2.413696e-05
S115   12  2.413696e-05
S108   13  2.782057e-05
S112   13  2.782057e-05
```

In real data, this would be extremely unlikely since it means there is no statistical noise in the data.  So a regression model is 


Gabriel

**Comment by evaesquinas** [comment]
Dear Dr. Hoffman, 

Thanks very much for your help. I updated to v.1.26 (the stable release in Bioconductor) and the errors are quite different.
In fact, when I run model 1, it appears something that I haven't seen: `Error in eval_f(x, ...): Downdated VtV is not positive definite` as well as the warning that you posted.
In fact, I have seen [here](http://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#penalizationhandling-complete-separation) that the origin of this error is from `glmer`, where there is complete separation in the model. 

In relation to the following warning..
```
# Warning messages:
# 1: In optwrap(optimizer, devfun, getStart(start, rho$pp), lower = rho$lower,  :
#  convergence code -4 from nloptwrap: NLOPT_ROUNDOFF_LIMITED: Roundoff errors led
# to a breakdown of the optimization algorithm. In this case, the returned minimum 
# may still be useful.  (e.g. this error occurs in NEWUOA if one tries to achieve 
# a tolerance too close to machine precision.)
```
**If the model doesn't fail (using all the genes, not taking only one as you did) but I get this warning**, the conclusion will be the same, right? That there is no variation within category.

What I don't understand is why the model fails when it has all the genes and this doesn't happen (although it gives you a warning) when you have 1 gene (as you tried). **How is this possible?** 

Just out of curiosity, **how did you choose gene 5?** (because if I choose gene 4, gene 6... I don't get the same warning and therefore, there is variance within category). The reason of my question is that I am trying to find a similar case in my real data to see the same effect, but I don't know how to find a gene without variation within category. 

Thanks in advance again

**Comment by GabrielHoffman** [comment]
Q1: This tells you that *at least* one gene failed.  But it unfortunately doesn't tell you which one

Q2: This failure for one gene causes a different error when it tries to assemble the results for multiple genes together.  That's why you see the error about the number of rows.  

This is not ideal, but in practice it almost never comes up.  Further filtering your data should remove the problematic genes.  With your simulated data, it means the simulations weren't very realistic because there was no random noise.  I don't know about your real data, but it likely has to do with including genes that should be excluded for some simple reason    

Q3: I did the analysis one gene at a time and found when it failed

```r
for(i in 1:nrow(cts.mat)){
	message(i)
	varPart <- fitExtractVarPartModel(cts.mat[i,,drop=FALSE], model2, pheno, quiet=TRUE)
}
```
I bet that the same issue is going to affect most of your problematic genes.

**Comment by GabrielHoffman** [comment]
You will all most never see these errors in real data...

**Q2:** 'no variation within category'.  For gene 1, all the expression values for category 1 are `-1.981364e-03`, and all the values for category 2 are `4.489186e-05`.  This means that there is no variance *within* category.  This almost never comes up in real data because there is always statistical and measurement noise.  This is just an issue with your simulations.

```r
S116    1 -1.981364e-03
S117    1 -1.981364e-03
S118    1 -1.981364e-03
S1      2  4.489186e-05
S2      2  4.489186e-05
S3      3  9.136233e-06
S4      3  9.136233e-06
S5      3  9.136233e-06
```

**Q1:** `dream()` and the underlying `lmer()` functions use iterative numerical methods to estimate parameters.  These methods can suffer from rounding errors when values are very small.  In this case, there is no variation within categories, so the residual variance is **zero**, or at least a very, very small number.  The exact value of the residual variance is different for each gene due to rounding.  So a value of *0* vs *1e-16* can cause different internal checks to fail so you get different warnings or errors.

Overall, I'm not concerned since it is extremely rare to encounter these issue in real data.  But I am looking into improving the error messages

Gabriel

**Comment by evaesquinas** [comment]
Thanks very much for your help and your explanations, I really appreciate it. 
After all these doubts, I think I understand better what it is going on with my real data, thanks.
